In [3]:
import numpy as np 
from scipy.sparse import  csc_matrix
row=np.array([0,1,2])
col=np.array([1,2,0])
data=np.array([8,9,16])
A=csc_matrix((data,(row,col)),shape=(3,3))
A.toarray()

array([[ 0,  8,  0],
       [ 0,  0,  9],
       [16,  0,  0]], dtype=int32)

In [4]:
row=np.array([1,0,2])
col=np.array([0,1,2])
data=np.array([6,2,8])
B=csc_matrix((data,(row,col)),shape=(3,3))
B.toarray()

array([[0, 2, 0],
       [6, 0, 0],
       [0, 0, 8]], dtype=int32)

In [5]:
AB=A.multiply(B)
AB.toarray()

array([[ 0, 16,  0],
       [ 0,  0,  0],
       [ 0,  0,  0]], dtype=int32)